name: common CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirm:
          description: 'Do You Wanna trigger this pipeline? (Type yes)'
          required: true

jobs:
  unit-test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: unit test
        run: sleep 5s & echo "run unit tests successfully"
  api-test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: api test
        run: sleep 3s & echo "run api tests successfully"
  build-image:
    runs-on: [ ubuntu-latest ]
    needs:
      - unit-test
      - api-test
    steps:
      - uses: actions/checkout@v2

      - name: api test
        run: sleep 10s & echo "build image successfully"
  
  deploy-dev:
    runs-on: [ ubuntu-latest ]
    needs:
      - build-image
    steps:
      - uses: actions/checkout@v2

      - name: deploy dev to  ${{ env.GITHUB_SHA }}
        run: sleep 5s & echo "deploy dev successfully"
  
  deploy-test:
    environment: test
    runs-on: [ ubuntu-latest ]
    needs:
      - deploy-dev
    steps:
      - name: deploy test to  ${{ env.GITHUB_SHA }}
        run: sleep 5s & echo "deploy test successfully"

  e2e-test:
    runs-on: [ ubuntu-latest ]
    needs:
      - deploy-test
    steps:
      - name: run e2e
        run: sleep 5s & echo "e2e test run successfully"

  
  deploy-uat:
    environment: uat
    runs-on: [ ubuntu-latest ]
    needs:
      - deploy-test
      - e2e-test
    steps:
      - name: deploy uat to  ${{ env.GITHUB_SHA }}
        run: sleep 5s & echo "deploy uat successfully"

  
  deploy-prod:
    environment: prod
    runs-on: [ ubuntu-latest ]
    needs:
      - deploy-uat
    steps:
      - name: deploy prod to  ${{ env.GITHUB_SHA }}
        run: sleep 5s & echo "deploy prod successfully"
